-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Sep 05, 2019 at 02:52 PM
-- Server version: 5.5.60-MariaDB
-- PHP Version: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `faq`
--

CREATE TABLE `faq` (
  `id` int(11) NOT NULL,
  `titre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contenu` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `faq`
--

INSERT INTO `faq` (`id`, `titre`, `contenu`, `created_at`) VALUES
(1, 'Certificat de non-gage, tarif de carte grise… Que dois-je faire ?', '<p>Le changement de l&eacute;gislation concernant la demande de&nbsp;<strong>carte grise</strong>&nbsp;engendre de nombreuses questions. <strong>CGOfficiel</strong> est un expert et vous propose quelques r&eacute;ponses &agrave; la vol&eacute;e ! A-t-on vraiment besoin d&rsquo;un&nbsp;<strong>certificat de non-gage</strong>&nbsp;? Le&nbsp;<strong>tarif d&rsquo;une carte grise</strong>&nbsp;d&eacute;pend-il de mon d&eacute;partement ? Existe-t-il une&nbsp;<strong>carte grise gratuite</strong>&nbsp;? Autant d&rsquo;interrogations que nous tentons d&rsquo;&eacute;claircir pour vous permettre d&rsquo;y voir un peu plus clair. Dans tous les cas pour vos d&eacute;marches, vous n&rsquo;avez plus besoin de perdre de temps pour votre&nbsp;<strong>carte grise</strong>. Pour profiter de tous nos avantages, venez nous voir et nous ferons ensemble toutes les formalit&eacute;s afin de vous procurer des documents en r&egrave;gle ! <strong>CGOfficiel</strong>&nbsp;est votre partenaire pour vous faciliter la vie.</p>\r\n\r\n<p>D&eacute;pendante du Minist&eacute;re de l&#39;Int&eacute;rieur, l&#39;Agence Nationale des Titres S&eacute;curis&eacute;s est l&#39;agence d&#39;&eacute;tat qui r&eacute;git les certificats d&#39;immatriculation (ex carte grise). Vous pouvez sur leur site suivre l&#39;&eacute;volution de votre carte grise en quelques minutes.<br />\r\nLes directives de l&#39;ANTS sont directement r&eacute;percut&eacute;es dans par la facon de faire des garages qui appliquent imm&eacute;diatement les r&egrave;gles.</p>', '2018-10-19 08:20:34'),
(2, 'Agrément du Trésor Public qu\'est ce que cela veut dire ?', '<p>Il est tr&egrave;s facile de suivre les diff&eacute;rentes d&eacute;marches pour le changement de nom sur la carte grise, lors d&#39;un achat de voitures d&rsquo;occasion. Il y a pourtant des r&egrave;gles pr&eacute;cises &agrave; respecter pour ne pas se tromper. Lorsqu&rsquo;on ne connait pas personnellement celui &agrave; qui on a achet&eacute; la voiture, mieux vaut rester sur ses gardes pour &eacute;viter les &eacute;ventuels ennuis.</p>\r\n\r\n<p>En premier lieu, il serait plus sage de v&eacute;rifier le num&eacute;ro de s&eacute;rie de la voiture inscrit sur le rep&egrave;re E de la carte et de le comparer avec celui de la voiture. Le num&eacute;ro de s&eacute;rie peut &ecirc;tre marqu&eacute; &agrave; plusieurs endroits sur une voiture, le moteur, les fen&ecirc;tres, etc&hellip; le mieux est de se renseigner sur la marque.</p>\r\n\r\n<p>Deuxi&egrave;mement, il faut absolument que le vendeur soit celui qui est inscrit sur le rep&egrave;re C.1 et s&rsquo;assurer que la personne qui a son nom inscrit sur le C.4.1 signe un certificat de cession en bonne et due forme. Ce n&rsquo;est qu&rsquo;apr&egrave;s toutes ces v&eacute;rifications que vous pourrez effectuer l&rsquo;achat du v&eacute;hicule en remplissant une d&eacute;claration de cession et barrant la carte. Il est important de souligner que si vous n&rsquo;&ecirc;tes pas inscrit l&eacute;galement en tant que propri&eacute;taire du v&eacute;hicule, vous ne pourrez pas proc&eacute;der au&nbsp;<strong>changement carte grise</strong>.</p>\r\n\r\n<p>En r&egrave;gle g&eacute;n&eacute;rale, le nouveau propri&eacute;taire a un mois &agrave; partir de la date o&ugrave; il a achet&eacute; la voiture pour changer de nom. L&rsquo;automobiliste pourra cependant circuler librement et sans aucun probl&egrave;me entre-temps avec les mentions &laquo; vendue le &raquo; qui ont &eacute;t&eacute; sign&eacute;es et dat&eacute;es par l&rsquo;ancien propri&eacute;taire. S&rsquo;il arrive que le d&eacute;lai soit d&eacute;pass&eacute;, le nouveau propri&eacute;taire encourra une amende de 11 Euros lors d&rsquo;un contr&ocirc;le de police avec une obligation de pr&eacute;sentation de la nouvelle carte dans les 5 jours qui suivront le contr&ocirc;le. Il est pourtant important de souligner que l&rsquo;amende n&rsquo;est pas imposable &agrave; l&rsquo;automobiliste s&rsquo;il pr&eacute;sente sa demande en retard.</p>', '2018-10-19 08:31:28'),
(3, 'Est-il possible de mettre, sur la carte grise, le nom d\'un mineur n\'ayant pas encore le permis ?', '<p>Oui, il est tout &agrave; fait possible de mettre le nom d&#39;une personne mineure sur la carte grise.&nbsp;<br />\r\nL&#39;article 2.II <em>de l&#39;arr&ecirc;t&eacute; du 5 novembre 1984</em> portant sur l&#39;immatriculation des v&eacute;hicules indique qu&#39;</p>\r\n\r\n<blockquote>\r\n<p>&quot;un v&eacute;hicule peut &ecirc;tre immatricul&eacute; au nom d&#39;un mineur&quot;</p>\r\n</blockquote>\r\n\r\n<p>Dans ce cas, la demande d&#39;immatriculation doit &ecirc;tre sign&eacute;e par la personne ou l&#39;institution investie de l&#39;autorit&eacute; parentale ou du droit de garde.</p>', '2018-10-22 15:43:13'),
(4, 'Quelques astuces pour un changement de carte grise', '<p>Mettre &agrave; jour et faire un&nbsp;<strong>changement carte grise</strong>&nbsp;peut se faire tr&egrave;s rapidement, le tout est de conna&icirc;tre les bonnes astuces. La premi&egrave;re chose &agrave; savoir par exemple lors d&rsquo;un achat de v&eacute;hicule d&rsquo;occasion est qu&rsquo;il est possible de faire sa demande en ligne. Plusieurs sites sp&eacute;cialis&eacute;s peuvent traiter vos demandes d&rsquo;immatriculations et&nbsp;<strong>changement carte grise</strong>. Faire confiance &agrave; des interm&eacute;diaires professionnels dans le domaine du changement carte grise peut &ecirc;tre tr&egrave;s b&eacute;n&eacute;fique. Pour avoir de l&#39;argent de c&ocirc;t&eacute;, il vaut mieux passer par eux, vous pourrez alors effectuer votre paiement par deux fois et selon les cas, vous pourrez m&ecirc;me le diviser par 3. Bien &eacute;videmment, le principal atout se trouve ailleurs, en effet, avec ces professionnels pour votre&nbsp;<strong>changement carte grise</strong>, vous recevrez beaucoup plus rapidement votre commande que lorsque vous la passer aux guichets ou par correspondance. Cependant, attention, il est interdit de r&eacute;aliser sa carte grise par internet. Vous devez physiquement vous rendre dans une agence, chez un professionnel qui vous aidera et/ou r&eacute;alisera vos d&eacute;marches avec et pour vous.</p>', '2018-10-22 16:03:54'),
(5, 'Agrément du Trésor Public qu\'est ce que cela veut dire ?', '<p>L&rsquo;agr&eacute;ment est une autorisation donn&eacute;e par le <strong>Tr&eacute;sor Public</strong> permettant au professionnel habilit&eacute; de percevoir les taxes et la redevance sur les certificats d&rsquo;immatriculation, sous forme d&eacute;mat&eacute;rialis&eacute;e via le syst&egrave;me d&rsquo;information de t&eacute;l&eacute;paiement &laquo;<strong> SIT</strong> &raquo; et de reverser les fonds par pr&eacute;l&egrave;vement bancaire &agrave; l&rsquo;administration des finances. Un professionnel agr&eacute;&eacute; conserve toujours la possibilit&eacute; de faire effectuer le paiement des taxes par la carte bancaire du particulier. La demande d&rsquo;agr&eacute;ment est effectu&eacute;e conjointement ou apr&egrave;s l&rsquo;habilitation &agrave; la t&eacute;l&eacute;transmission <strong>SIV</strong>. L&rsquo;agr&eacute;ment fait l&rsquo;objet d&rsquo;une convention particuli&egrave;re, dite &laquo; convention d&rsquo;agr&eacute;ment &raquo;, compl&eacute;mentaire de la convention d&rsquo;habilitation. Pour un meilleur suivi de leurs op&eacute;rations et limiter les risques li&eacute;s au paiement CB (rejets, fraudes, etc.), il est recommand&eacute; aux professionnels habilit&eacute;s d&rsquo;opter pour l&rsquo;agr&eacute;ment et le pr&eacute;l&egrave;vement SEPA.</p>', '2018-10-23 10:06:51'),
(6, 'A quoi sert le certificat d\'immatriculation', '<p>Le certificat d&rsquo;immatriculation est un document qui affiche toutes les informations concernant votre v&eacute;hicule tel que le num&eacute;ro de ch&acirc;ssis, le type de v&eacute;hicule, le nom et l&rsquo;adresse du propri&eacute;taire ainsi que le num&eacute;ro de plaque d&rsquo;immatriculation. Il est en quelque sorte la carte d&rsquo;identit&eacute; de votre voiture. Il indique que votre voiture est immatricul&eacute;e aupr&egrave;s de la <em>Direction d&rsquo;Immatriculation des V&eacute;hicules</em> (<strong>DIV</strong>). Afin de mettre un v&eacute;hicule en circulation, il vous faut ce document, car il peut vous &ecirc;tre r&eacute;clam&eacute; en cas de contr&ocirc;le des autorit&eacute;s. En effet, si vous circulez sans le certificat d&rsquo;immatriculation, vous risquez une amende importante.</p>\r\n\r\n<p>Depuis 2009, on a mis en place un nouveau syst&egrave;me d&rsquo;immatriculation&nbsp;: le <strong>SIV</strong> ou <em>Syst&egrave;me d&rsquo;Immatriculation des V&eacute;hicules</em>. Ce changement a pour objectif de simplifier et de moderniser tout le syst&egrave;me d&rsquo;immatriculation des v&eacute;hicules fran&ccedil;ais. Le certificat d&rsquo;immatriculation est de couleur grise et jaune depuis <u>septembre 2013</u>. Il se compose ainsi en deux parties, &agrave; savoir&nbsp;:</p>\r\n\r\n<ul>\r\n	<li><em>La section avec le symbole de voiture qui doit toujours rester dans le v&eacute;hicule</em></li>\r\n	<li><em>La section avec le symbole maison que vous devez garder chez vous</em></li>\r\n</ul>\r\n\r\n<p>En somme, le certificat d&rsquo;immatriculation est une preuve que votre v&eacute;hicule a &eacute;t&eacute; enregistr&eacute; &agrave; la <strong>DIV </strong>et qu&rsquo;il est autoris&eacute; &agrave; circuler sur la voie publique. Il est valable pendant toute l&rsquo;utilisation du v&eacute;hicule &agrave; conditions que certaines informations ne changent pas. Au cas o&ugrave; il y a un changement de propri&eacute;taire, ce dernier doit &eacute;diter un nouveau certificat d&rsquo;immatriculation.</p>', '2018-12-05 12:06:33'),
(7, 'Doit-on immatriculer une remorque?', '<p>L&rsquo;obligation de faire immatriculer une remorque d&eacute;pend de son poids.</p>\r\n\r\n<p>En effet, une caravane ou une remorque (agricole ou non) ayant un poids total autoris&eacute; en charge (<strong>PTAC</strong>) <strong>sup&eacute;rieur &agrave; 500 kg</strong>, doit &ecirc;tre immatricul&eacute;e. Ainsi, elle doit avoir sa propre immatriculation, diff&eacute;rente de celle du v&eacute;hicule tracteur.</p>\r\n\r\n<p>Pour qu&rsquo;elle soit autoris&eacute;e &agrave; circuler, elle doit avoir son propre certificat d&rsquo;immatriculation.</p>\r\n\r\n<p>Les d&eacute;marches sont les m&ecirc;mes que celles pr&eacute;vues pour une voiture particuli&egrave;re ou une voiture d&#39;occasion, neuve ou d&rsquo;occasion. La remorque ou la caravane doit avoir une plaque min&eacute;ralogique reprenant le num&eacute;ro d&#39;immatriculation de son certificat d&rsquo;immatriculation. En revanche, l&rsquo;identifiant r&eacute;gional peut &ecirc;tre diff&eacute;rent de celui du v&eacute;hicule tracteur. Une fois votre remorque immatricul&eacute;e, vous conserverez ce certificat d&#39;immatriculation dans le v&eacute;hicule tracteur et fixerez ensuite la plaque d&#39;immatriculation &agrave; l&#39;arri&egrave;re de votre remorque. La remorque doit subir un premier contr&ocirc;le technique. Ensuite, un nouveau contr&ocirc;le technique sera n&eacute;cessaire tous les ans.</p>\r\n\r\n<p>Il est &agrave; noter qu&rsquo;une remorque, dont le <strong>PTAC </strong>est <strong>inf&eacute;rieur ou &eacute;gal &agrave; 500 kg</strong>, n&rsquo;a pas besoin d&rsquo;un certificat d&rsquo;immatriculation. Aucun contr&ocirc;le technique n&rsquo;est n&eacute;cessaire. Toutefois, votre remorque doit disposer d&#39;un duplicata de la plaque d&#39;immatriculation du v&eacute;hicule tracteur. Elle doit &eacute;galement &ecirc;tre en r&egrave;gle par rapport au code de la route. Il faut savoir aussi qu&rsquo;une remorque de moins de 500 kg de <strong>PTAC </strong>faite &laquo;&nbsp;<em>maison&nbsp;</em>&raquo; doit &ecirc;tre homologu&eacute;e pour pouvoir circuler.</p>\r\n\r\n<p>Vous devez alors contacter la <em>Direction R&eacute;gionale de l&rsquo;Environnement, de l&rsquo;Am&eacute;nagement et du Logement</em> (<strong>DREAL</strong>) pour l&rsquo;homologation.</p>', '2018-12-05 12:08:57'),
(8, 'Doit-on immatriculer une voiture sans permis?', '<p>Une voiture qui ne n&eacute;cessite pas de permis de conduire doit disposer malgr&eacute; tout d&#39;une carte grise pour pouvoir circuler sur la voie publique. En effet, le certificat d&rsquo;immatriculation est obligatoire pour circuler au volant d&rsquo;une &laquo;&nbsp;<em>voiturette&nbsp;</em>&raquo;.</p>\r\n\r\n<p>Les d&eacute;marches sont identiques &agrave; celles d&rsquo;une voiture classique, qu&rsquo;elle soit neuve ou d&rsquo;occasion. En effet, une voiture sans permis doit disposer d&#39;une plaque d&#39;immatriculation &agrave; l&rsquo;arri&egrave;re afin de l&rsquo;identifier. Cependant, l&#39;installation d&#39;une plaque &agrave; l&#39;avant n&#39;est pas obligatoire. La composition des plaques d&rsquo;immatriculation est la m&ecirc;me qu&rsquo;une plaque d&rsquo;immatriculation pour une voiture classique, &agrave; savoir&nbsp;: une euro-bande &agrave; gauche, le num&eacute;ro d&rsquo;immatriculation et l&rsquo;identifiant territorial avec num&eacute;ro du d&eacute;partement.</p>\r\n\r\n<p>Le co&ucirc;t d&rsquo;immatriculation d&rsquo;une voiture sans permis varie en fonction de la r&eacute;gion dans laquelle vous r&eacute;sidez. Vous disposez d&rsquo;un d&eacute;lai d&rsquo;un mois pour faire &eacute;tablir le certificat d&rsquo;immatriculation de votre voiture sans permis. Pass&eacute;e cette p&eacute;riode, vous risquez une amende forfaitaire de 135 euros, qui peut &ecirc;tre major&eacute;e &agrave; 750 euros pour d&eacute;faut de plaque d&rsquo;immatriculation.</p>\r\n\r\n<p>Il est bon de savoir que les v&eacute;hicules identifi&eacute;s comme voiture sans permis sont des quadricycles l&eacute;gers de deux places. Ces petites voitures sont g&eacute;n&eacute;ralement &eacute;quip&eacute;es d&rsquo;un moteur de 50 cm<sup>3</sup>. Leur puissance n&rsquo;exc&egrave;de ainsi pas 4 kW, soit 5,6 chevaux, limitant leur vitesse maximum &agrave; 45 km/h.</p>\r\n\r\n<p>On peut conduire une voiture sans permis d&egrave;s l&rsquo;&acirc;ge de 16 ans. Cependant, les conducteurs n&eacute;s apr&egrave;s 1988 doivent &ecirc;tre d&eacute;tenteurs du permis AM et effectuer une formation pratique de 7 heures sans examen.</p>', '2018-12-05 12:10:10'),
(9, 'Qu\'est ce qu\'un certificat provisoire d\'immatriculation?', '<p>Comme son nom l&rsquo;indique, <em>un certificat provisoire d&rsquo;immatriculation</em> (<strong>CPI</strong>) est une carte grise provisoire permettant d&rsquo;identifier le v&eacute;hicule, mais aussi de circuler sur la voie publique.</p>\r\n\r\n<p>Tout comme le certificat d&rsquo;immatriculation, le <strong>CPI </strong>n&rsquo;est pas un titre de propri&eacute;t&eacute;, bien qu&rsquo;il soit &eacute;tabli au nom du propri&eacute;taire du v&eacute;hicule. Comme pour le certificat d&rsquo;immatriculation, on trouve &eacute;galement les informations suivantes&nbsp;dans le <strong>CPI </strong>: le num&eacute;ro d&rsquo;immatriculation, l&rsquo;identit&eacute; du propri&eacute;taire, les caract&eacute;ristiques du v&eacute;hicule ainsi que la date de la premi&egrave;re immatriculation. Il permet uniquement de circuler en France, en attendant de recevoir le certificat d&rsquo;immatriculation d&eacute;finitif.</p>\r\n\r\n<p>De ce fait, vous ne pourrez pas circuler &agrave; l&rsquo;&eacute;tranger avec un <strong>CPI</strong>. En somme, que le v&eacute;hicule soit neuf ou d&rsquo;occasion, le certificat d&rsquo;immatriculation provisoire est remis &agrave; son acqu&eacute;reur, en attendant la r&eacute;ception de la carte grise d&eacute;finitive &agrave; son domicile.</p>\r\n\r\n<p>On peut demander un <strong>CPI </strong>lors d&rsquo;un changement d&rsquo;adresse exigeant l&rsquo;&eacute;mission d&rsquo;un nouveau certificat d&rsquo;immatriculation, d&rsquo;une demande du duplicata du certificat d&rsquo;immatriculation ou encore d&rsquo;une demande d&rsquo;un nouveau certificat d&rsquo;immatriculation en cas d&rsquo;erreur ou d&rsquo;usurpation de plaques.</p>\r\n\r\n<p>En revanche, on ne peut pas demander un <strong>CPI </strong>pour l&rsquo;immatriculation d&rsquo;une voiture import&eacute;e. Si votre <strong>CPI </strong>est expir&eacute; <em>(il n&rsquo;est valide que pour une dur&eacute;e d&rsquo;un mois)</em>, et que vous n&rsquo;avez pas encore re&ccedil;u votre carte grise d&eacute;finitive, vous risquez d&rsquo;avoir une amende en cas de contr&ocirc;le routier. Avec la mise en place du <strong>SIV</strong>, le certificat d&rsquo;immatriculation est envoy&eacute; &agrave; votre domicile sous pli s&eacute;curis&eacute;. Vous ne pourrez plus vous rendre en pr&eacute;fecture mais les demandes en ligne sur le site&nbsp;<a href=\"http://dev.cgofficiel.fr/\" target=\"_blank\">www.cgofficiel.fr</a>&nbsp;simplifieront vos d&eacute;marches.</p>', '2018-12-05 12:13:20');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `faq`
--
ALTER TABLE `faq`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `faq`
--
ALTER TABLE `faq`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
